# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-18 14:26
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='goods/banners/', verbose_name='图片')),
                ('index', models.IntegerField(default=1, verbose_name='图片轮播的顺序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '首页的轮播图',
                'verbose_name_plural': '首页的轮播图',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='商品名称')),
                ('goods_brief', models.CharField(blank=True, max_length=200, null=True, verbose_name='商品简单描述')),
                ('goods_sn', models.CharField(blank=True, max_length=50, null=True, verbose_name='商品编号')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击量')),
                ('sold_num', models.IntegerField(default=0, verbose_name='销售量')),
                ('goods_num', models.IntegerField(default=0, verbose_name='库存')),
                ('fav_num', models.IntegerField(default=0, verbose_name='收藏数')),
                ('market_price', models.FloatField(default=0.0, verbose_name='市场价格')),
                ('shop_price', models.FloatField(default=0.0, verbose_name='本店价格')),
                ('goods_front_image', models.ImageField(blank=True, max_length=200, null=True, upload_to='goods/imags/')),
                ('goods_desc', DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='内容')),
                ('ship_free', models.BooleanField(default=True, verbose_name='是否包邮费')),
                ('is_new', models.BooleanField(default=False, verbose_name='是否新商品')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否热销商品')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='类别的名称')),
                ('code', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='类别编码code')),
                ('category_type', models.IntegerField(choices=[(1, '一级商品类别'), (2, '二级商品类别'), (3, '三级商品类别')], verbose_name='商品类别')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='类别描述')),
                ('is_tab', models.BooleanField(default=False, verbose_name='是否添加到导航栏')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='goods.GoodsCategory', verbose_name='父级商品类目')),
            ],
            options={
                'verbose_name': '商品类别',
                'verbose_name_plural': '商品类别',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategoryBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='品牌的名称')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='品牌的描述')),
                ('image', models.ImageField(max_length=200, upload_to='goods/brands/')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='goods.GoodsCategory', verbose_name='商品类别')),
            ],
            options={
                'db_table': 'goods_goodsbrand',
                'verbose_name': '商品品牌',
                'verbose_name_plural': '商品品牌',
            },
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='goods/goodsimages/', verbose_name='图片')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.Goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品的轮播图',
                'verbose_name_plural': '商品的轮播图',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory', verbose_name='商品类别'),
        ),
        migrations.AddField(
            model_name='banner',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='商品'),
        ),
    ]
