# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-24 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifycode',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='注册邮箱'),
        ),
    ]
